[package]
name = "backend-security"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
jsonwebtoken = "9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres", "uuid", "chrono"] }
dotenvy = "0.15"
argon2 = "0.5"
redis = { version = "0.24", features = ["tokio-comp"] }
uuid = { version = "1.4", features = ["v4", "serde"] }
